### ISSUE TITLE
KEGG Pathways broken

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange-bio#112]
##### Orange version

3.4.6-dev

##### Orange-Bioinformatics version

2.6.21

##### Expected behavior
KEGG Pathways widget works.

##### Actual behavior
KEGG is broken and doesn't work.

##### Steps to reproduce the behavior
Geo Datasets (G1210) - KEGG.

##### Additional info (worksheets, data, screenshots, ...)
Traceback (most recent call last):
  File "/Users/ajda/orange/orange-bio/orangecontrib/bio/widgets3/OWKEGGPathwayBrowser.py", line 713, in _onEnrichTaskFinished
    self._enrichTask.result()
  File "/Users/ajda/orange/orange3/Orange/widgets/utils/concurrent.py", line 317, in result
    return self._future.result(timeout)
  File "/Users/ajda/anaconda/envs/o3/lib/python3.5/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/Users/ajda/anaconda/envs/o3/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/Users/ajda/orange/orange3/Orange/widgets/utils/concurrent.py", line 327, in _execute
    result = self.run()
  File "/Users/ajda/orange/orange3/Orange/widgets/utils/concurrent.py", line 308, in run
    return self.function()
  File "/Users/ajda/orange/orange-bio/orangecontrib/bio/widgets3/OWKEGGPathwayBrowser.py", line 703, in <lambda>
    run_enrichment(org_code, genes, reference, progress)
  File "/Users/ajda/orange/orange-bio/orangecontrib/bio/widgets3/OWKEGGPathwayBrowser.py", line 691, in run_enrichment
    pathways.keys(), progress_callback=progress
  File "/Users/ajda/orange/orange-bio/orangecontrib/bio/kegg/databases.py", line 239, in pre_cache
    self.api.get(batch)
  File "/Users/ajda/orange/orange-bio/orangecontrib/bio/kegg/caching.py", line 184, in __call__
    rval = self.function(self.instance, *args)
  File "/Users/ajda/orange/orange-bio/orangecontrib/bio/kegg/api.py", line 394, in get
    return self._batch_get(ids)
  File "/Users/ajda/orange/orange-bio/orangecontrib/bio/kegg/api.py", line 447, in _batch_get
    entries = [store[key].value for key in keys]
  File "/Users/ajda/orange/orange-bio/orangecontrib/bio/kegg/api.py", line 447, in <listcomp>
    entries = [store[key].value for key in keys]
  File "/Users/ajda/orange/orange-bio/orangecontrib/bio/kegg/caching.py", line 63, in __getitem__
    raise KeyError(key)
KeyError: "get('path:hsa00300',)"

**Comment by jerneju** [comment]
https://sentry.io/biolab/orange-bio/issues/321446712/
