### ISSUE TITLE
Error Orange.bio arrayexpress.query_experiments(accession='E-MEXP-31')

### ISSUE THREAD

**Issue by pengyu** [biolab/orange-bio#28]
I have the following Orange Bioinformatics code.

```
#!/usr/bin/env python

from Orange.bio import arrayexpress
print arrayexpress.query_experiments(accession='E-MEXP-31')
```

But when I run it using Python 2.7.8, it shows up the following error.

```
Traceback (most recent call last):
  File "./main.py", line 4, in <module>
    print arrayexpress.query_experiments(accession='E-MEXP-31')
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/orangecontrib/bio/arrayexpress.py", line 354, in query_experiments
    return parse_json(io.TextIOWrapper(stream, ecoding="utf-8"))
TypeError: 'ecoding' is an invalid keyword argument for this function
```

Does anybody know how to fix the problem? Thanks.

**Comment by markotoplak** [comment]
We (probably I) made a typo when I was maintaining this code. The bug is now fixed. Please install the latex orange-bioinformatics version.

Thanks for reporting the bug!

**Comment by pengyu** [comment]
I got this when I try to install it. Is there anything wrong?

```
$ sudo pip install --upgrade Orange-Bioinformatics
Password:
Downloading/unpacking Orange-Bioinformatics from https://pypi.python.org/packages/source/O/Orange-Bioinformatics/Orange-Bioinformatics-2.6.5.tar.gz#md5=431ec94e9ade2ad50cd78c3d42a5ca78
  Downloading Orange-Bioinformatics-2.6.5.tar.gz (2.8MB): 2.8MB downloaded
  Running setup.py (path:/private/tmp/pip_build_root/Orange-Bioinformatics/setup.py) egg_info for package Orange-Bioinformatics

    warning: no files found matching '*' under directory 'tests'
    warning: no files found matching '*.txt'
Requirement already up-to-date: Orange in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from Orange-Bioinformatics)
Requirement already up-to-date: setuptools in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools-17.0-py2.7.egg (from Orange-Bioinformatics)
Requirement already up-to-date: numpy in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from Orange-Bioinformatics)
Requirement already up-to-date: scipy in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from Orange-Bioinformatics)
Requirement already up-to-date: six in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from Orange-Bioinformatics)
Requirement already up-to-date: genesis-pyapi>=1.1.2 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from Orange-Bioinformatics)
Requirement already up-to-date: slumber>=0.7.1 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from Orange-Bioinformatics)
Requirement already up-to-date: requests>=2.6.0 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from Orange-Bioinformatics)
Requirement already up-to-date: singledispatch in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from Orange-Bioinformatics)
Installing collected packages: Orange-Bioinformatics
  Found existing installation: Orange-Bioinformatics 2.6.4
    Uninstalling Orange-Bioinformatics:
      Successfully uninstalled Orange-Bioinformatics
  Running setup.py install for Orange-Bioinformatics

    warning: no files found matching '*' under directory 'tests'
    warning: no files found matching '*.txt'
    Skipping installation of /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/orangecontrib/__init__.py (namespace package)
    Skipping installation of /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/orangecontrib/bio/__init__.py (namespace package)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/orangecontrib/bio/widgets3/OWBioMart.py", line 772
        print("Task failed with:", exception, file=sys.stderr)
                                                  ^
    SyntaxError: invalid syntax

      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/orangecontrib/bio/widgets3/OWFeatureSelection.py", line 82
        def score_anova(*arrays, axis=0):
                                    ^
    SyntaxError: invalid syntax

      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/orangecontrib/bio/widgets3/OWMAPlot.py", line 427
        print("Error: ", error, file=sys.stderr)
                                    ^
    SyntaxError: invalid syntax

      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/orangecontrib/bio/widgets3/OWSetEnrichment.py", line 700
        print("ERROR:", exception, file=sys.stderr)
                                       ^
    SyntaxError: invalid syntax

    Installing /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Orange_Bioinformatics-2.6.5-py2.7-nspkg.pth
Successfully installed Orange-Bioinformatics
Cleaning up...
```
